import figlet from "figlet";

export const FIGLET_FONTS: {name: string, value: figlet.Fonts}[] = [
  { name: "3-d", value: "3-D" },
  { name: "3x5", value: "3x5" },
  { name: "5 Line Oblique", value: "5 Line Oblique" },
  { name: "Acrobatic", value: "Acrobatic" },
  { name: "Alligator", value: "Alligator" },
  { name: "Alligator2", value: "Alligator2" },
  { name: "Alphabet", value: "Alphabet" },
  { name: "ANSI Shadow", value: "ANSI Shadow"},
  { name: "Avatar", value: "Avatar" },
  { name: "Banner", value: "Banner" },
  { name: "Banner3", value: "Banner3" },
  { name: "Banner4", value: "Banner4" },
  { name: "Barbwire", value: "Barbwire" },
  { name: "Basic", value: "Basic" },
  { name: "Bell", value: "Bell" },
  { name: "Big", value: "Big" },
  { name: "Big Chief", value: "Big Chief" },
  { name: "Binary", value: "Binary" },
  { name: "Block", value: "Block" },
  { name: "Bloody", value: "Bloody"},
  { name: "Bubble", value: "Bubble" },
  { name: "Bulbhead", value: "Bulbhead" },
  { name: "Caligraphy", value: "Caligraphy" },
  { name: "Catwalk", value: "Catwalk" },
  { name: "chunky", value: "Chunky" },
  { name: "Coinstak", value: "Coinstak" },
  { name: "Colossal", value: "Colossal" },
  { name: "Computer", value: "Computer" },
  { name: "Contessa", value: "Contessa" },
  { name: "Contrast", value: "Contrast" },
  { name: "Cosmike", value: "Cosmike" },
  { name: "Cricket", value: "Cricket" },
  { name: "Cursive", value: "Cursive" },
  { name: "Cyberlarge", value: "Cyberlarge" },
  { name: "Cybermedium", value: "Cybermedium" },
  { name: "Cybersmall", value: "Cybersmall" },
  { name: "Diamond", value: "Diamond" },
  { name: "Digital", value: "Digital" },
  { name: "Doh", value: "Doh" },
  { name: "Doom", value: "Doom" },
  { name: "Dot Matrix", value: "Dot Matrix" },
  { name: "Dr Pepper", value: "Dr Pepper" },
  { name: "Efti Chess", value: "Efti Chess" },
  { name: "Efti Font", value: "Efti Font" },
  { name: "Efti Piti", value: "Efti Piti" },
  { name: "Efti Robot", value: "Efti Robot" },
  { name: "Efti Italic", value: "Efti Italic" },
  { name: "Efti Wall", value: "Efti Wall" },
  { name: "Efti Water", value: "Efti Water" },
  { name: "Epic", value: "Epic" },
  { name: "Fender", value: "Fender" },
  { name: "Four Tops", value: "Four Tops" },
  { name: "Fuzzy", value: "Fuzzy" },
  { name: "Goofy", value: "Goofy" },
  { name: "Gothic", value: "Gothic" },
  { name: "Graffiti", value: "Graffiti" },
  { name: "Greek", value: "Greek" },
  { name: "NT Greek", value: "NT Greek" },
  { name: "Hollywood", value: "Hollywood" },
  { name: "Invita", value: "Invita" },
  { name: "Isometric1", value: "Isometric1" },
  { name: "Isometric2", value: "Isometric2" },
  { name: "Isometric3", value: "Isometric3" },
  { name: "Isometric4", value: "Isometric4" },
  { name: "Italic", value: "Italic" },
  { name: "Ivrit", value: "Ivrit" },
  { name: "Jazmine", value: "Jazmine" },
  { name: "Jerusalem", value: "Jerusalem" },
  { name: "Katakana", value: "Katakana" },
  { name: "Kban", value: "Kban" },
  { name: "Larry 3D", value: "Larry 3D" },
  { name: "LCD", value: "LCD" },
  { name: "Lean", value: "Lean" },
  { name: "Letters", value: "Letters" },
  { name: "Linux", value: "Linux" },
  { name: "Lockergnome", value: "Lockergnome" },
  { name: "Madrid", value: "Madrid" },
  { name: "Marquee", value: "Marquee" },
  { name: "Maxfour", value: "Maxfour" },
  { name: "Mike", value: "Mike" },
  { name: "Mini", value: "Mini" },
  { name: "Mirror", value: "Mirror" },
  { name: "Mnemonic", value: "Mnemonic" },
  { name: "Morse", value: "Morse" },
  { name: "Moscow", value: "Moscow" },
  { name: "Nancyj", value: "Nancyj" },
  { name: "Nipples", value: "Nipples" },
  { name: "NT Greek", value: "NT Greek" },
  { name: "O8", value: "O8" },
  { name: "Ogre", value: "Ogre" },
  { name: "Pawp", value: "Pawp" },
  { name: "Peaks", value: "Peaks" },
  { name: "Pebbles", value: "Pebbles" },
  { name: "Pepper", value: "Pepper" },
  { name: "Poison", value: "Poison" },
  { name: "Puffy", value: "Puffy" },
  { name: "Pyramid", value: "Pyramid" },
  { name: "Rectangles", value: "Rectangles" },
  { name: "Relief", value: "Relief" },
  { name: "Relief2", value: "Relief2" },
  { name: "Roman", value: "Roman" },
  { name: "Rot13", value: "Rot13" },
  { name: "Rounded", value: "Rounded" },
  { name: "Rowan Cap", value: "Rowan Cap" },
  { name: "Rozzo", value: "Rozzo" },
  { name: "Runic", value: "Runic" },
  { name: "Runyc", value: "Runyc" },
  { name: "S Blood", value: "S Blood" },
  { name: "Script", value: "Script" },
  { name: "Serifcap", value: "Serifcap" },
  { name: "Shadow", value: "Shadow" },
  { name: "Short", value: "Short" },
  { name: "Slant", value: "Slant" },
  { name: "Slide", value: "Slide" },
  { name: "SL Script", value: "SL Script" },
  { name: "Small", value: "Small" },
  { name: "Keyboard", value: "Keyboard" },
  { name: "Speed", value: "Speed" },
  { name: "Stampatello", value: "Stampatello" },
  { name: "Standard", value: "Standard" },
  { name: "Star Wars", value: "Star Wars" },
  { name: "Stellar", value: "Stellar" },
  { name: "Stop", value: "Stop" },
  { name: "Straight", value: "Straight" },
  { name: "Tanja", value: "Tanja" },
  { name: "Tengwar", value: "Tengwar" },
  { name: "Term", value: "Term" },
  { name: "Thick", value: "Thick" },
  { name: "Thin", value: "Thin" },
  { name: "Three Point", value: "Three Point" },
  { name: "Ticks", value: "Ticks" },
  { name: "Tinker-Toy", value: "Tinker-Toy" },
  { name: "Tombstone", value: "Tombstone" },
  { name: "Trek", value: "Trek" },
  { name: "Tsalagi", value: "Tsalagi" },
  { name: "Two Point", value: "Two Point" },
  { name: "Univers", value: "Univers" },
  { name: "USA Flag", value: "USA Flag" },
  { name: "Wavy", value: "Wavy" },
  { name: "Weird", value: "Weird" },
]
